---
version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "--- %(asctime)s - %(levelname)s - %(module)s.%(funcName)s\n    %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout

    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: simple
        filename: log_info.txt
        # maxBytes: 10485760 # 10MB
        # maxBytes: 10240 # 10KB
        maxBytes: 10240 # 10KB
        backupCount: 5
        encoding: utf8

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: simple
        filename: log_error.txt
        maxBytes: 10485760 # 10MB
        backupCount: 5
        encoding: utf8

loggers:
    etmtk:
        level: ERROR
        handlers: [console]
        propagate: no

root:
    level: DEBUG
    handlers: [console, info_file_handler, error_file_handler]
